name: "Terraform deploy"

trigger:
  branches:
    include:
    - master
pool:
  vmImage: 'ubuntu-latest'
stages: 
- stage: plan
  displayName: "Plan stage"
  jobs:
  - job: plan
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 0.13.2'
      inputs:
        terraformVersion: 0.13.2
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm'
      inputs:
        provider: azurerm
        command: init
        backendServiceArm: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendAzureRmResourceGroupName: 'rg-perm-common-sand-john-01'
        backendAzureRmStorageAccountName: statetfsandboxjohn01
        backendAzureRmContainerName: terraform
        backendAzureRmKey: terraform.tfstate
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm'
      inputs:
        command: plan
        commandOptions: -out=tfplan
        environmentServiceNameAzureRM: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendServiceArm: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendAzureRmResourceGroupName: 'rg-perm-common-sand-john-01'
        backendAzureRmStorageAccountName: statetfsandboxjohn01
        backendAzureRmContainerName: terraform
        backendAzureRmKey: terraform.tfstate
    - task: CopyFiles@2
      displayName: 'Copy terraform plan to artifact store'
      inputs:
        Contents: tfplan
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish plan to artifacts'
      inputs:
        PathToPublish: '$(build.artifactstagingdirectory)'