name: "Terraform deploy"

trigger:
  branches:
    include:
    - master
pool:
  vmImage: 'ubuntu-latest'
stages: 
- stage: plan
  displayName: "Plan stage"
  jobs:
  - job: plan
    steps:
    - bash: echo "hello"
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform 0.13.2'
      inputs:
        terraformVersion: 0.13.2
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm'
      inputs:
        command: init
        workingDirectory: '$(System.DefaultWorkingDirectory)/_Terraform-CI/drop/Terraform'
        backendServiceArm: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendAzureRmResourceGroupName: 'rg-perm-common-sand-john-01'
        backendAzureRmStorageAccountName: statetfsandboxjohn01
        backendAzureRmContainerName: tfstatesandjohn01
        backendAzureRmKey: $(secrets.sotrageaccesskey)
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terraform : azurerm'
      inputs:
        command: plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/_Terraform-CI/drop/Terraform'
        commandOptions: '-out=Terraform/plan'
        environmentServiceNameAzureRM: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendServiceArm: 'PaaS-Sandbox-John (5ffae18c-eeb0-4706-8a03-0a823e6cccb5)'
        backendAzureRmResourceGroupName: 'rg-perm-common-sand-john-01'
        backendAzureRmStorageAccountName: statetfsandboxjohn01
        backendAzureRmContainerName: tfstatesandjohn01
        backendAzureRmKey: $(secrets.storageaccesskey)
    - task: CopyFiles@2
      displayName: 'Copy terraform plan to artifacts'
      inputs:
        SourceFolder: 'Terraform'
        Contents: 'plan'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish plan'
      inputs:
        PathToPublish: '$(build.artifactstagingdirectory)'