name: "[dev] tftest"

on:
  push

jobs:
  "CI":
    runs-on: ubuntu-latest
    env:
      TF_VAR_client_secret: ${{ secrets.SPTERRAFORMCICD_PROD }}
      TF_VAR_state_access_key: ${{ secrets.SPTERRAFORMCICD_STATE_STORAGE_ACCOUNT }}
      TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TARGET: ./
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.2
      - run: terraform init -backend-config='access_key=${{ secrets.SPTERRAFORMCICD_STATE_STORAGE_ACCOUNT }}' -backend-config=./backend.hcl $TARGET
      - run: terraform validate $TARGET
      - run: terraform plan $TARGET
